<script setup lang="ts">
import { computed, ref, watch, onMounted, nextTick } from "vue";
import { useFormRules, useNaiveForm } from "@/hooks/common/form";
import type { FormRules, FormItemRule, FormInst } from 'naive-ui';
import {
  fetchAddBanRule,
  fetchUpdateBanRule,
} from "@/service/api";
import { $t } from "@/locales";
import { useThemeStore } from '@/store/modules/theme';

defineOptions({
  name: "YidunRecordDetailDrawer",
});

interface Props {
  /** the type of operation */
  operateType: NaiveUI.TableOperateType;
  /** the edit row data */
  rowData?: any | null;
  /** 外部传入的只读 */
  readonly?: boolean;
}

const props = defineProps<Props>();

interface Emits {
  (e: "submitted"): void;
}

const emit = defineEmits<Emits>();

const visible = defineModel<boolean>("visible", {
  default: false,
});

const { formRef, validate, restoreValidation } = useNaiveForm();
const { defaultRequiredRule } = useFormRules();

// 配置类型选项
const configTypeOptions = [
  { label: '时间窗口', value: 'TIME_WINDOW' },
  { label: '惩罚规则', value: 'PENALTY_RULE' }
];

// 时间单位选项
const timeUnitOptions = [
  { label: '分钟', value: 'MINUTE' },
  { label: '小时', value: 'HOUR' },
  { label: '天', value: 'DAY' },
  { label: '月', value: 'MONTH' },
  { label: '年', value: 'YEAR' }
];

// 时间单位映射
const timeUnitMap: Record<string, string> = {
  'MINUTE': '分钟',
  'HOUR': '小时',
  'DAY': '天',
  'MONTH': '月',
  'YEAR':'年'
};

// 动态验证规则
const dynamicRules = computed(() => {
  const baseRules: Record<string, FormRules | FormItemRule> = {
    configType: {
      required: true,
      message: '请选择配置类型',
      trigger: ['change', 'blur']
    },
    description: {
      required: true,
      message: '请输入描述',
      trigger: ['input', 'blur']
    },
    configValue: {
      required: true,
      message: '请输入配置数值',
      trigger: ['blur'],
      validator: (rule: FormItemRule, value: any) => {
        if (value === null || value === undefined || value === '') {
          return new Error('配置数值不能为空');
        }
        if (isNaN(value)) {
          return new Error('配置数值必须是数字');
        }
        const numValue = Number(value);
        if (numValue < 1) {
          return new Error('配置数值必须大于0');
        }
        return true;
      }
    },
    timeUnit: {
      required: true,
      message: '请选择时间单位',
      trigger: ['change', 'blur']
    },
  };

  // 只有惩罚规则才需要验证违规次数
  if (model.value.configType === 'PENALTY_RULE') {
    baseRules.banCount = {
      required: true,
      message: '请输入违规次数',
      trigger: ['blur'],
      validator: (rule: FormItemRule, value: any) => {
        if (value === null || value === undefined || value === '') {
          return new Error('违规次数不能为空');
        }
        if (isNaN(value)) {
          return new Error('违规次数必须是数字');
        }
        const numValue = Number(value);
        if (numValue < 1) {
          return new Error('违规次数必须大于0');
        }
        return true;
      }
    };
  }

  return baseRules;
});

// 判断是否为只读模式
const readonlyMode = computed(() => {
  return props.readonly || false;
});

const title = computed(() => {
  const titles: Record<NaiveUI.TableOperateType, string> = {
    add: "新增封禁规则",
    edit: "编辑封禁规则",
  };
  return titles[props.operateType];
});

type Model = {
  configType: string;
  description: string;
  configValue: number | null;
  timeUnit: string;
  banCount: number | null;
};

const model = ref(createDefaultModel());

// 自动生成描述
function autoGenerateDescription() {
  if (!model.value.configType) {
    return;
  }

  const timeUnitText = timeUnitMap[model.value.timeUnit] || model.value.timeUnit;

  if (model.value.configType === 'TIME_WINDOW') {
    // 时间窗口描述
    if (model.value.configValue && model.value.timeUnit) {
      model.value.description = `封禁统计时间窗口范围，${model.value.configValue}${timeUnitText}`;
    } else {
      model.value.description = '';
    }
  } else if (model.value.configType === 'PENALTY_RULE') {
    // 惩罚规则描述
    if (model.value.banCount && model.value.configValue && model.value.timeUnit) {
      model.value.description = `违规${model.value.banCount}次，封禁时长${model.value.configValue}${timeUnitText}`;
    } else {
      model.value.description = '';
    }
  }
}

// 监听配置类型变化
watch(() => model.value.configType, (newVal) => {
  autoGenerateDescription();
  // 重置验证
  nextTick(() => {
    restoreValidation();
  });
});

// 监听违规次数变化
watch(() => model.value.banCount, () => {
  autoGenerateDescription();
});

// 监听配置数值变化
watch(() => model.value.configValue, () => {
  autoGenerateDescription();
});

// 监听时间单位变化
watch(() => model.value.timeUnit, () => {
  autoGenerateDescription();
});

function createDefaultModel(): Model {
  return {
    configType: "PENALTY_RULE",
    description: "",
    configValue: null,
    timeUnit: "DAY",
    banCount: null
  };
}

function closeDrawer() {
  visible.value = false;
}

async function handleSubmit() {
  try {
    // 验证表单
    await formRef.value?.validate();

    // 准备提交数据 - 确保数值类型正确
    const submitData = {
      id: props.rowData?.id, // 编辑时需要传递ID
      configType: model.value.configType,
      description: model.value.description,
      configValue: model.value.configValue !== null ? Number(model.value.configValue) : null,
      timeUnit: model.value.timeUnit,
      banCount: model.value.banCount !== null ? Number(model.value.banCount) : null
    };

    console.log('提交数据:', submitData); // 调试用

    let response;
    if (props.operateType === "add") {
      response = await fetchAddBanRule(submitData);
    } else {
      response = await fetchUpdateBanRule(submitData);
    }

    // 检查接口返回的响应
    if (response && response.response.data.code === 200) {
      window.$message?.success(props.operateType === "add" ? "新增成功" : "修改成功");
      closeDrawer();
      emit("submitted");

      // 重置表单
      model.value = createDefaultModel();
    } else {
      // 接口返回了错误
      const errorMsg = response.response.data.msg || response.response.data.message || "操作失败";
      window.$message?.error(errorMsg);
      console.error('接口返回错误:', response);
    }
  } catch (error) {
    console.error('提交失败:', error);
    if (error instanceof Error) {
      window.$message?.error(`提交失败: ${error.message}`);
    } else {
      window.$message?.error("提交失败，请检查表单数据");
    }
  }
}

// 监听弹窗显示/隐藏
watch(visible, async (newVal) => {
  if (newVal) {
    restoreValidation();

    if (props.operateType === 'edit' && props.rowData) {
      const data = props.rowData;

      // 从后端数据转换为前端数据格式
      model.value = {
        configType: data.configType || 'PENALTY_RULE',
        description: data.description || '',
        configValue: data.configValue !== undefined && data.configValue !== null ? Number(data.configValue) : null,
        timeUnit: data.timeUnit || 'DAY',
        banCount: data.banCount !== undefined && data.banCount !== null ? Number(data.banCount) : null
      };

      // 如果编辑时描述为空，自动生成一次
      if (!data.description) {
        autoGenerateDescription();
      }
    } else {
      // 新增时重置表单
      model.value = createDefaultModel();
    }
  } else {
    // 关闭时重置验证
    if (formRef.value) {
      formRef.value.restoreValidation();
    }
  }
}, { immediate: true });

const themeStore = useThemeStore();
</script>

<template>
  <NModal v-model:show="visible" :title="title" preset="card" class="w-1200px">
    <NScrollbar class="h-700px pr-20px">
      <NForm
        ref="formRef"
        :model="model"
        :rules="dynamicRules"
        label-placement="left"
        :label-width="100"
        require-mark-placement="right-hanging"
      >
        <NGrid responsive="screen" item-responsive>
          <!-- 配置类型 -->
          <NFormItemGi
            span="24 m:12"
            label="配置类型"
            path="configType"
            :required="true"
          >
            <NSelect
              v-model:value="model.configType"
              :options="configTypeOptions"
              placeholder="请选择配置类型"
              clearable
              :disabled="readonlyMode || (operateType === 'edit' && model.configType === 'TIME_WINDOW')"
            />
            <template #feedback>
              <div v-if="model.configType === 'TIME_WINDOW'" style="color: #999; font-size: 12px;">
                注意：时间窗口配置只能有一条记录
              </div>
            </template>
          </NFormItemGi>

          <!-- 违规次数（仅惩罚规则显示） -->
          <NFormItemGi
            v-if="model.configType === 'PENALTY_RULE'"
            span="24 m:12"
            label="违规次数"
            path="banCount"
            :required="true"
          >
            <NInputNumber
              v-model:value="model.banCount"
              placeholder="请输入违规次数"
              :min="1"
              style="width: 100%"
              :disabled="readonlyMode"
              :show-button="false"
            />
            <template #feedback>
              <div style="color: #999; font-size: 12px;">
                例如：1表示第1次违规
              </div>
            </template>
          </NFormItemGi>

          <!-- 配置数值 -->
          <NFormItemGi
            span="24 m:12"
            :label="model.configType === 'TIME_WINDOW' ? '窗口时长' : '封禁时长'"
            path="configValue"
            :required="true"
          >
            <NInputNumber
              v-model:value="model.configValue"
              :placeholder="model.configType === 'TIME_WINDOW' ? '请输入窗口时长数值' : '请输入封禁时长数值'"
              :min="1"
              style="width: 100%"
              :disabled="readonlyMode"
              :show-button="false"
            />
            <template #feedback>
              <div style="color: #999; font-size: 12px;">
                请输入大于0的数值
              </div>
            </template>
          </NFormItemGi>

          <!-- 时间单位 -->
          <NFormItemGi
            span="24 m:12"
            label="时间单位"
            path="timeUnit"
            :required="true"
          >
            <NSelect
              v-model:value="model.timeUnit"
              :options="timeUnitOptions"
              placeholder="请选择时间单位"
              :disabled="readonlyMode"
            />
          </NFormItemGi>

          <!-- 描述 -->
          <NFormItemGi
            span="24 m:12"
            label="描述"
            path="description"
            :required="true"
          >
            <NInput
              v-model:value="model.description"
              :placeholder="model.configType === 'TIME_WINDOW' ? '请输入时间窗口描述' : '请输入惩罚规则描述'"
              :disabled="readonlyMode"
            />
            <template #feedback>
              <div style="color: #999; font-size: 12px;">
                描述将根据您的选择自动生成
              </div>
            </template>
          </NFormItemGi>

          <!-- 有效期预览 -->
          <NFormItemGi
            span="24"
            label="有效期预览"
            v-if="model.configValue && model.timeUnit"
          >
            <div style="padding: 8px 12px; background: #f5f5f5; border-radius: 4px;">
              {{ model.configType === 'TIME_WINDOW' ?
              `统计时间窗口：${model.configValue} ${timeUnitMap[model.timeUnit] || model.timeUnit}` :
              `封禁时长：${model.configValue} ${timeUnitMap[model.timeUnit] || model.timeUnit}`
              }}
            </div>
          </NFormItemGi>

        </NGrid>
      </NForm>
    </NScrollbar>
    <template #footer>
      <NSpace justify="end" :size="16">
        <NButton @click="closeDrawer">{{ $t("common.cancel") }}</NButton>
        <NButton
          type="primary"
          @click="handleSubmit"
          :disabled="readonlyMode"
        >
          {{ $t("common.confirm") }}
        </NButton>
      </NSpace>
    </template>
  </NModal>
</template>

<style scoped>
.n-input--disabled {
  cursor: not-allowed;
}
</style>
